<?php

return [
    'selected' => [
        "Harley-Davidson",
        "BMW",
        "Ducati",
        "Honda",
        "KTM",
        "Kawasaki",
        "Suzuki",
        "Yamaha",
        "Indian",
        "Triumph",
    ],
    'all' => [
        "AJP",
        "Adiva",
        "Aeon",
        "Aprilia",
        "Aspess Power",
        "Axy",
        "Azel",
        "BMW",
        "Bajaj",
        "Benelli",
        "Beta",
        "Bimota",
        "Borile",
        "Boss Hoss",
        "Buell",
        "Bultaco",
        "CCM",
        "CF Moto",
        "CH Racing",
        "CMC",
        "CPI",
        "CR&S",
        "Cagiva",
        "Dado Motors",
        "Daelim",
        "Derbi",
        "Ducati",
        "E-Tropolis",
        "E-max",
        "Ecomission",
        "Fantic Motor",
        "Garelli",
        "Gas Gas",
        "Generic",
        "Ghezzi-Brian",
        "GiMotori",
        "GiPuma",
        "Gilera",
        "Green Mobility Italia",
        "HDM",
        "HM",
        "HP Power",
        "Harley-Davidson",
        "Headbanger",
        "Honda",
        "Honda Dall'Ara",
        "Hupper",
        "Husaberg",
        "Husqvarna",
        "Hyosung",
        "Indian",
        "Italjet",
        "Jawa",
        "KRC",
        "KTM",
        "Kawasaki",
        "Kawasaki KL",
        "Keeway",
        "Kreidler",
        "Kymco",
        "LML",
        "Lambretta",
        "Laverda",
        "Leonart",
        "Lingben",
        "Linhai",
        "MBK",
        "MV Agusta",
        "MZ",
        "Magni",
        "Maico",
        "Malaguti",
        "Mash",
        "Millepercento",
        "Mondial",
        "Montesa",
        "Moto Bellini",
        "Moto Guzzi",
        "Moto Morini",
        "Moto Rumi",
        "MotoBi",
        "Motom",
        "Motor Union",
        "Nipponia",
        "Norton",
        "Nox",
        "Ossa",
        "Over",
        "PGO",
        "Paton",
        "Peda Motor",
        "Peugeot",
        "Piaggio",
        "Polini",
        "Quadro",
        "Quantya",
        "RedMoto Honda",
        "Renault",
        "Rieju",
        "Royal Enfield",
        "SWM",
        "Sachs",
        "Scorpa",
        "Sherco",
        "Siamoto",
        "Steed",
        "Suzuki",
        "Suzuki Valenti",
        "Sym",
        "TGB",
        "TM Racing",
        "Terra Modena",
        "Triumph",
        "Ural",
        "Vectrix",
        "Vertemati",
        "Victory",
        "Vor",
        "WT Motors",
        "Yamaha",
    ]
];
